apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-back
  template:
    metadata:
      labels:
        app: task-manager-back
    spec:
      containers:
        - name: task-manager-back
          image: dehmanim/task-manager-back:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: task-manager-mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-manager-mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: taskmanagerdb

