apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-back
  template:
    metadata:
      labels:
        app: task-manager-back
    spec:
      containers:
        - name: task-manager-back
          image: task-manager-back
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
